name: MLOps CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'   # ✅ FIXED

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run model training
      run: |
        python src/train_model.py
